---
- name: OS hardening
  hosts: all
  become: true

  tasks:
    # - name: Set a login banner
    #   copy:
    #     dest: "{{ item }}"
    #     src: etc/issue
    #     owner: root
    #     group: root
    #     mode: 0644
    #   with_items:
    #     - /etc/issue
    #     - /etc/issue.net

    # - name: Add hardened SSH config
    #   copy:
    #     dest: /etc/ssh/sshd_config
    #     src: etc/ssh/sshd_config
    #     owner: root
    #     group: root
    #     mode: 0600
    #   notify: Reload SSH

    # - name: Write pwquality.conf
    #   copy:
    #     src: etc/security/pwquality.conf
    #     dest: /etc/security/pwquality.conf
    #     owner: root
    #     group: root
    #     mode: "u=rw,go=r"

    - name: Add to PAM config
      lineinfile:
        path: "{{ item }}"
        regexp: '^password.*pam_pwquality\.so'
        insertbefore: '^password.*pam_unix\.so'
        line: "password    requisite                                    pam_pwquality.so retry=5"
        owner: root
        group: root
        mode: "u=rw,go=r"
      with_items:
        - "/etc/authselect/system-auth"
        - "/etc/authselect/password-auth"

  handlers:
    - name: Reload SSH
      service:
        name: sshd
        state: reloaded
